storage:
  location: fileuploaer
  host: localhost
  port: 5432
  db: fileuploader
  username: postgres
  password: postgres
  type: filesystem
  max-files-size: 104857600 # 100 MB

spring:
  mvc:
    pathmatch:
      use-suffix-pattern: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/filevault}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8180/realms/filevault/protocol/openid-connect/certs}
